// Each icon is decorative (aria-hidden + focusable="false"); the accessible
// name lives on the surrounding control. Colour comes from `currentColor`.

export { default as IconLogo } from './IconLogo.vue'
export { default as IconMoon } from './IconMoon.vue'
export { default as IconSun } from './IconSun.vue'
export { default as IconPlus } from './IconPlus.vue'
export { default as IconCalendar } from './IconCalendar.vue'
export { default as IconChevronUp } from './IconChevronUp.vue'
export { default as IconChevronDown } from './IconChevronDown.vue'
export { default as IconChevronLeft } from './IconChevronLeft.vue'
export { default as IconCheckSquare } from './IconCheckSquare.vue'
export { default as IconSearch } from './IconSearch.vue'
export { default as IconFilter } from './IconFilter.vue'
export { default as IconRows } from './IconRows.vue'
export { default as IconColumns } from './IconColumns.vue'
export { default as IconCheck } from './IconCheck.vue'
export { default as IconMoreVertical } from './IconMoreVertical.vue'
export { default as IconEdit } from './IconEdit.vue'
export { default as IconTrash } from './IconTrash.vue'
export { default as IconAlertCircle } from './IconAlertCircle.vue'
export { default as IconClose } from './IconClose.vue'
export { default as IconUser } from './IconUser.vue'
export { default as IconGripVertical } from './IconGripVertical.vue'
export { default as IconFolder } from './IconFolder.vue'
